#!/bin/sh
#
#Simcom module dialing script
#Software version V1.0.1
#


xx=0
en=0 #调试开关：0关闭，1打开 ，2输出到文件
outfile="/tmp/slklog1"	#输出文件
Debug()
{
	tim=$(date "+%Y-%m-%d %H:%M:%S")	#获取系统时间
	if [ $en == 1 ]; then
		echo $tim $1					#打印输出
	elif [ $en == 2 ]; then
		echo $tim $1 >> $outfile		#输出到文件
	fi
}

#############################################
#											#
#				进入主函数					#
#											#
#############################################
while [ 1 ]
do
	Debug "网络诊断"
	ping -c 1 -w 1 down.xxorg.com #获取openvpn接口名称
	if [ $? -eq 0 ]; then 
		
		for a in $(opkg print-architecture | awk '{print $2}'); do
			case "$a" in
				all|noarch)
					;;
				aarch64_armv8-a|arm_arm1176jzf-s_vfp|arm_arm926ej-s|arm_cortex-a15_neon-vfpv4|arm_cortex-a5|arm_cortex-a53_neon-vfpv4|arm_cortex-a7_neon-vfpv4|arm_cortex-a8_vfpv3|arm_cortex-a9|arm_cortex-a9_neon|arm_cortex-a9_vfpv3|arm_fa526|arm_mpcore|arm_mpcore_vfp|arm_xscale|armeb_xscale|ipq)
					ARCH="arm"
					;;
				i386_pentium|i386_pentium4)
					ARCH="386"
					;;
				ar71xx|mips_24kc|mips_mips32|mips64_octeon)
					ARCH="mips"
					;;
				mipsel_24kc|mipsel_24kec_dsp|mipsel_74kc|mipsel_mips32|mipsel_1004kc_dsp|ramips_1004kc|ramips_24kec)
					ARCH="mipsle"
					;;
				x86_64)
					ARCH="amd64"
					;;
				*)
					exit 0
					;;
			esac
		done
		Debug "查看内核版本：$ARCH"
		if [ ! -f "/var/etc/frpc/frpc" ]; then
			mkdir -p "/var/etc/frpc" 
			wget -c http://down.xxorg.com/frp/frp_0.25.1/frp_0.25.1_linux_$ARCH/frpc -O /var/etc/frpc/frpc &
			Debug "下载frpc服务"
			sleep 10s
		fi
		if [ $(uci -q get frpc.main.enabled) == "1"	]; then #读取frpc开启使能
			Debug "frpc服务：启用"
			sleep 1s
			client_file=$(uci -q get frpc.main.client_file)
			Debug "$client_file"
			if [ $(pgrep -f $client_file | wc -l) -eq 0 ];then
				Debug "frpc未运行"
				/etc/init.d/frpc restart &
				Debug "frpc重启"
				sleep 10s
			else
				break
			fi
		else
			break
		fi
	fi
	sleep 15s
done
	



