VERSION    =  2.00
CC       =  gcc
DEBUG      =  
CFLAGS     =  
SOURCES	   =  main.c
INCLUDES   =  
LIB_NAMES  =  
LIB_PATH   =  
OBJ        =  $(SOURCES:.c=.o)
TARGET     =  slkmac2

#links
$(TARGET):$(OBJ)
	$(CC) $(SOURCES) -o $(TARGET) $(LIB_NAMES)
	
#compile
%.o: %.c
	$(CC) $(INCLUDES) $(DEBUG) -c $(CFLAGS) $< -o $@

.PHONY:clean
clean:
	@echo "Remove linked and compiled files......"
	rm -rf $(OBJ) $(TARGET) output 


