#!/bin/sh /etc/rc.common
START=50

run_reboot()
{
	local enable
	config_get_bool enable $1 enable

	if [ $enable == 1 ]; then
		local minute
		local hour

		config_get minute $1 minute
		config_get hour $1 hour

		sed '/reboot/ d' /etc/crontabs/root > /tmp/crontab_admin_tmp
		cp /tmp/crontab_admin_tmp /etc/crontabs/admin
		echo "$minute $hour * * * reboot &" >> /etc/crontabs/admin

		echo "Auto REBOOT has started."
		/etc/init.d/cron restart
	else
		sed '/reboot/ d' /etc/crontabs/admin > /tmp/crontab_admin_tmp
		cp /tmp/crontab_admin_tmp /etc/crontabs/admin
		echo "Deltele  REBOOT has started."
		/etc/init.d/cron restart
	fi
}

start()
{
	config_load autoreboot
	config_foreach run_reboot login
}

stop()
{
	echo "Auto REBOOT has stoped."
}
