#!/bin/sh
uci batch <<-EOF
	set network.pptp=interface
	set network.pptp.proto='pptp'
	set network.pptp.auto='0'
	set network.pptp.metric='8'
	set network.l2tp=interface
	set network.l2tp.proto='l2tp'
	set network.l2tp.auto='0'
	set network.l2tp.metric='9'
	set network.openvpn=interface
	set network.openvpn.enable='0'
	set network.openvpn.ifname='tun0'
	set network.gre=interface
	set network.gre.proto='gretap'
	set network.gre.auto='0'
	set network.gre_static=interface
	set network.gre_static.proto='static'
	set network.gre_static.ifname='gre-gre'
	set network.wan.proto='dhcp'
	set network.wwan=interface
	set network.wwan.ifname='-'
	set network.wwan.proto='dhcp'
	set network.lan.ifname='eth1 eth2 eth3 eth4'
	set network.wan.ifname='eth0'
	set network.wan.metric='10'
    commit network
EOF



