#!/bin/sh /etc/rc.common
START=30
STOP=80

start()
{	
	cpu=$(cat /proc/cpuinfo |grep "system type" |grep "MT7628AN" |wc -l)
	if [ $cpu -ge 1 ]; then
		echo "0" > /sys/class/gpio/export
		echo "out" > /sys/class/gpio/gpio0/direction
		echo 1 > /sys/class/gpio/gpio0/value
		
		echo "2" > /sys/class/gpio/export
		echo "out" > /sys/class/gpio/gpio2/direction
		echo 1 > /sys/class/gpio/gpio2/value
		
		echo "3" > /sys/class/gpio/export
		echo "out" > /sys/class/gpio/gpio3/direction
		echo 1 > /sys/class/gpio/gpio3/value
	fi
}

