#!/bin/sh
uci batch <<-EOF
	set wireless.wifi1.htmode='HT40'
	set wireless.wifi0.htmode='HT80'
	set wireless.wifi0.channel='40'
	set wireless.wifi1.channel='3'
	set wireless.sta0=wifi-iface
	set wireless.sta0.device='wifi1'
	set wireless.sta0.ifname='ath11'
	set wireless.sta0.mode='sta'
	set wireless.sta0.network='wific'
	set wireless.sta0.disabled='1'

	set network.wific=interface
	set network.wific.proto='dhcp'
	set network.wific.metric='40'
	set network.wific.ifname='-'
	
	add_list firewall.@zone[1].network='wific'

    commit network
    commit wireless
    commit firewall
	sync
EOF
