#
# Copyright (C) 2008-2014 The LuCI Team <luci@lists.subsignal.org>
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=Serial-for-IPQ
LUCI_DEPENDS:=+ser2net +modbus +slkcli
PKG_VERSION:=1.0
PKG_RELEASE:=3

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
